name: climtas
channels:
    - conda-forge
    - coecms
dependencies:
    - python >= 3.6
    - dask
    - netcdf4
    - pandas
    - scipy
    - tqdm
    - xarray
    - typing_extensions
    - cfunits
    - iris
    - mule
    - sparse
    - black
    - nbsphinx
    - sphinx-book-theme
