{% set data = load_setup_py_data() %}

package:
    name: climtas
    version: {{ data.get('version') }}

source:
    path: .


build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
    host:
        - python
        - pip
    run:
        - python >=3.6
        - dask
        - netcdf4
        - pandas
        - scipy
        - tqdm
        - xarray

test:
    imports:
        - climtas
    requires:
        - pytest
        - coverage
    files:
        - setup.cfg
        - test
        - README.rst
        - doc
    script_env:
        - TEST_OUTPUT
    commands:
        - COVERAGE_FILE=${TEST_OUTPUT:-.}/coverage coverage run --source climtas -m pytest ./test --pyargs climtas --junit-xml=${TEST_OUTPUT:-.}/pytest/junit.xml

