version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
        environment:
            TEST_OUTPUT: /tmp/artifacts
        steps:
            - checkout
            - run: conda install conda-build conda-verify codecov
            - run: |
                mkdir -p ${TEST_OUTPUT}
                conda build . -c conda-forge -c coecms
            - run: 
                name: Upload codecov
                command: |
                    coverage combine ${TEST_OUTPUT}/coverage
                    coverage xml -o ${TEST_OUTPUT}/coverage.xml
                    codecov -f ${TEST_OUTPUT}/coverage.xml
                when: always
            - store_artifacts:
                path: /tmp/artifacts
            - store_test_results:
                path: /tmp/artifacts/pytest
            - persist_to_workspace:
                root: /opt/conda/conda-bld
                paths: 
                    - '*/*.tar.bz2'
    black-check:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run: |
                cd ~
                mkdir -p bin
                wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
                ~/bin/micromamba shell init -s bash -p ~/micromamba
            - run: |
                source ~/.bashrc
                micromamba --help
                micromamba activate
                micromamba install black
            - run:
                name: Checking if 'black' needs to be run
                command: |
                    source ~/.bashrc
                    micromamba activate
                    black --check --diff .
                when: always
    mypy-check:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run: |
                cd ~
                mkdir -p bin
                wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
                ~/bin/micromamba shell init -s bash -p ~/micromamba
            - run: |
                source ~/.bashrc
                micromamba install mypy xarray
            - run:
                name: Type checking with mypy
                command: |
                    source ~/.bashrc
                    mypy
                when: always

    publish:
        docker:
            - image: continuumio/miniconda3
        steps:
            - attach_workspace:
                at: /tmp/artifacts

            - run: conda install anaconda-client
            - run: |
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /tmp/artifacts/*/*.tar.bz2

workflows:
    version: 2
    ci-check:
        jobs:
            - black-check
            - mypy-check
            # - build:
            #     filters:
            #         tags:
            #             only: /.*/
            # - publish:
            #     context: conda-publish
            #     requires:
            #         - build
            #     filters:
            #         tags:
            #             only: /.*/
            #         branches:
            #             ignore: /.*/
