version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
        environment:
            TEST_OUTPUT: /tmp/artifacts
        steps:
            - checkout
            - run: conda install conda-build conda-verify codecov black
            - run: |
                mkdir -p ${TEST_OUTPUT}
                conda build .
            - run:
                name: Checking if 'black' needs to be run
                command: black --check --diff .
                when: always
            - run: 
                name: Upload codecov
                command: |
                    coverage combine ${TEST_OUTPUT}/coverage
                    coverage xml -o ${TEST_OUTPUT}/coverage.xml
                    codecov -f ${TEST_OUTPUT}/coverage.xml
                when: always
            - store_artifacts:
                path: /tmp/artifacts
            - store_test_results:
                path: /tmp/artifacts/pytest
