version: 2
jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        environment:
            TEST_OUTPUT: /tmp/artifacts
        steps:
            - checkout
            - run: |
                cd ~
                mkdir -p bin micromamba
                wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
                eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                micromamba activate
                micromamba install conda-build conda-verify codecov -c conda-forge
            - run: |
                eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                micromamba activate
                mkdir -p ${TEST_OUTPUT}
                conda build . -c conda-forge -c coecms
            - run: 
                name: Upload codecov
                command: |
                    eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                    micromamba activate
                    coverage combine ${TEST_OUTPUT}/coverage
                    coverage xml -o ${TEST_OUTPUT}/coverage.xml
                    codecov -f ${TEST_OUTPUT}/coverage.xml
                when: always
            - store_artifacts:
                path: /tmp/artifacts
            - store_test_results:
                path: /tmp/artifacts/pytest
            - persist_to_workspace:
                root: /home/circleci/micromamba/conda-bld
                paths: 
                    - '*/*.tar.bz2'
    black-check:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run: |
                cd ~
                mkdir -p bin micromamba
                wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
                eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                micromamba activate
                micromamba install black -c conda-forge
            - run:
                name: Checking if 'black' needs to be run
                command: |
                    eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                    micromamba activate
                    black --check --diff .
                when: always
    mypy-check:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run: |
                cd ~
                mkdir -p bin micromamba
                wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
                eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                micromamba activate
                micromamba install mypy xarray -c conda-forge
            - run:
                name: Type checking with mypy
                command: |
                    eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                    micromamba activate
                    mypy
                when: always

    publish:
        docker:
            - image: cimg/base:2020.01
        steps:
            - attach_workspace:
                at: /tmp/artifacts
            - run: |
                cd ~
                mkdir -p bin micromamba
                wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
                eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                micromamba activate
                micromamba install anaconda-client -c conda-forge
            - run: |
                eval "$(~/bin/micromamba shell hook -s bash -p ~/micromamba)"
                micromamba activate
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /tmp/artifacts/*/*.tar.bz2

workflows:
    version: 2
    ci-check:
        jobs:
            - black-check
            - mypy-check
            - build:
                filters:
                    tags:
                        only: /.*/
            - publish:
                context: conda-publish
                requires:
                    - build
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
