version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
        environment:
            TEST_OUTPUT: /tmp/artifacts
        steps:
            - checkout
            - run: conda install conda-build conda-verify codecov
            - run: |
                mkdir -p ${TEST_OUTPUT}
                conda build . -c conda-forge -c coecms
            - run: 
                name: Upload codecov
                command: |
                    coverage combine ${TEST_OUTPUT}/coverage
                    coverage xml -o ${TEST_OUTPUT}/coverage.xml
                    codecov -f ${TEST_OUTPUT}/coverage.xml
                when: always
            - store_artifacts:
                path: /tmp/artifacts
            - store_test_results:
                path: /tmp/artifacts/pytest
            - persist_to_workspace:
                root: /tmp/artifacts
                paths: 
                    - '*.tar.bz2'
    black-check:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout
            - run: conda install black
            - run:
                name: Checking if 'black' needs to be run
                command: black --check --diff .
                when: always
    mypy-check:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout
            - run: conda install mypy xarray
            - run:
                name: Type checking with mypy
                command: mypy
                when: always

    publish:
        docker:
            - image: continuumio/miniconda3
        steps:
            - attach_workspace:
                at: /tmp/artifacts

            - run: conda install anaconda-client
            - run: |
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /tmp/artifacts/*.tar.bz2

workflows:
    version: 2
    ci-check:
        jobs:
            - black-check
            - mypy-check
            - build
                filters:
                    tags:
                        only: /.*/
            - publish:
                requires:
                    - build
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
